"""likes dislikes

Revision ID: 13a4f5fab1d0
Revises: d0ee5a086c8f
Create Date: 2019-07-17 18:19:51.311582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13a4f5fab1d0'
down_revision = 'd0ee5a086c8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ideas', sa.Column('dislikes', sa.Integer(), nullable=True, default=0))
    op.add_column('ideas', sa.Column('likes', sa.Integer(), nullable=True, default=0))
    op.add_column('ideas', sa.Column('skips', sa.Integer(), nullable=True, default=0))
    with op.batch_alter_table('ideas') as batch_op:
        batch_op.drop_column('num_rates')
        batch_op.drop_column('rating')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ideas', sa.Column('rating', sa.INTEGER(), nullable=True))
    op.add_column('ideas', sa.Column('num_rates', sa.INTEGER(), nullable=True))
    with op.batch_alter_table('ideas') as batch_op:
        batch_op.drop_column('skips')
        batch_op.drop_column('likes')
        batch_op.drop_column('dislikes')
    # ### end Alembic commands ###
